userprofile/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    # re_path('', views.userLogin, name='login'),
    re_path('login/', views.userLogin, name='login'),
    re_path('logout/', views.userLogout, name='logout'),
    re_path('info/', views.userInfo, name='info'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from web import views


app_name = 'article'

urlpatterns = [
    re_path('^index$', views.index, name='index'),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^article/$', views.index, name='index'),
    re_path(r'^article$', views.index, name='index'),
    re_path(r'^article/(\d*)', views.article, name='article'),
    re_path(r'^readme$', views.readme, name='readme'),
    re_path(r'^diary$', views.diary_index, name='diary_index'),
    re_path(r'^diary/(\d*)', views.article_diary, name='diary'),
]

yuki_no_home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path("", include(('web.urls', 'web'), namespace='web')),
    re_path('user/', include(('userprofile.urls', 'userprofile'), namespace='userprofile'))
]

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from userprofile.forms import UserLoginForm


# Create your views here.

def userLogin(request):
    # 如果请求时post请求
    if request.method == "POST":
        # 获取用户提交的请求
        user_login_form = UserLoginForm(data=request.POST)
        # 如果用户提交的请求数据合法
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 验证输入的用户名和密码在数据库中是否一致
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 登录成功
                login(request, user)
                return redirect('userprofile:info')
            else:
                # 登录失败
                return HttpResponse("登录失败，用户名或密码错误")
        else:
            return HttpResponse("登录失败，用户名或密码不合法")
    elif request.method == "GET":
        # 如果是get请求
        user_login_form = UserLoginForm()
        content = {'form': user_login_form}
        return render(request, 'userprofile/login.html', content)
    else:
        return HttpResponse("请使用post/get请求")


# 用户登出
def userLogout(request):
    logout(request)
    return redirect("article:index")


def userInfo(request):
    return render(request, "userprofile/info.html")

templates/userprofile/info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>个人中心</title>

    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/info.css" %}>
    <script src={% static "js/jquery-1.12.4.min.js" %}></script>
    <script src={% static "js/bootstrap.min.js" %}></script>
	

</head>
<body>
    {% if user.is_authenticated %}
	<!-- 导航栏 -->
    <div class="navbar navbar-inverse navbar-static-top">		
		<div class="container">
			
			<!-- 定义logo和切换小图标   -->
			<div class="navbar-header">

				<button class="navbar-toggle" data-toggle="collapse" data-target="#mymenu">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<!-- <a href="#" class="navbar-brand">LOGO</a> -->
			</div>

			<div class="collapse navbar-collapse" id="mymenu">
				<!-- 定义菜单   -->
				<ul class="nav navbar-nav">
					<li><a href="/index">首页</a></li>
					<li><a href="#">日记</a></li>
					<li><a href="#">关于</a></li>
					<li><a href="#">留言</a></li>
					<li><a href="logout/">注销</a></li>
				</ul>
			</div>
		</div>
	</div>

	<!-- 座右铭 -->
	<div class="container motto">
		<p>绷不住了家人们，这真是典中典，整活的带哥太能处了属于是。虽然不知道家人们如何评价，但我真是搁这笑啦了。不喜欢的家人们也摇了我吧我先润了。
		</p>
		<p> </p>
		<p class="p_right">
			《出处什么的已经不重要了》
		</p>
	</div>

	<!-- 主站内容 -->
	<div id="zan-bodyer">
		<div class="container">
			<div class="row">
                <!-- 只有这里改了 -->
                <!-- 用户信息 -->
                <div class="mainstay col-md-12">
                    <div id="userinfo">
                        <div id="username">
							<p>欢迎回来~ 初雪</p>
						</div>
                        <div id="userprofile">一堆信息</div>
                    </div>
                </div>

			</div>
		</div>
	</div>
    {% else %}
        <li class="nav-item">
            <a class="nav-link no-access" href="{% url 'userprofile:login' %}">非法访问,请登录</a>
        </li>
    {% endif %}

	<span class="pid">ID:80414367</span>

</body>
</html>

templates/userprofile/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/login.css" %}>
    <script src={% static "js/jquery-1.12.4.min.js" %}></script>
    <title>用户登录</title>
</head>
<body>
    <div id="login_view">
        <form method="post" action="login">
            {% csrf_token %}
            <img src={% static "images/login.png" %}>
            <input class="form-control" type="text" name="username" id="username" placeholder="请输入用户名:">
            <input class="form-control" type="password" name="password" id="password" placeholder="请输入密码:">
            <button type="submit" class="btn btn-primary mybtn">登录</button>
        </form>
        <button type="submit" class="btn btn-primary mybtn"> <a href="/index" style="color: white">返回</a> </button>
    </div>
</body>
</html>