web/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from web import views


app_name = 'article'

urlpatterns = [
    re_path('^index$', views.index, name='index'),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^article/$', views.index, name='index'),
    re_path(r'^article$', views.index, name='index'),
    re_path(r'^article/(\d*)', views.article, name='article'),
    re_path(r'^readme$', views.readme, name='readme'),
    re_path(r'^diary$', views.diary_index, name='diary_index'),
    re_path(r'^diary/(\d*)', views.article_diary, name='diary'),
]

yuki_no_home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path("", include(('web.urls', 'web'), namespace='web')),
    re_path('user/', include(('userprofile.urls', 'userprofile'), namespace='userprofile'))
]

templates/web/article.html
{% extends "web/base.html" %}
{% load static %}
{% block title %}
    {{ art.title }}
{% endblock title %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static '/css/article.css' %}>
{% endblock css %}


{% block content %}
    <div class="article">
        <div class="article-title">
            <p>{{ art.title }}</p>
        </div>
        <div class="tags">
                {% for tag in art.tags.all %}
                    <a href={% url 'article:index' %}?tag={{ tag }}><span class="label label-primary">{{ tag }}</span></a>
                {% endfor %}
        </div>
        <div class="article-content">
            <div class="contents">
                <!-- 缺文章 -->
                {{ art.text|safe }}
            </div>
        </div>
    </div>
{% endblock content %}

templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>#}
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href={% static '/css/bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static '/css/index.css' %}>
    {% block css %}{% endblock %}
    <link rel="stylesheet" type="text/css" href={% static '/css/font-awesome.min.css '%}>
    <script type="text/javascript" src={% static '/js/jquery-1.12.4.min.js' %}></script>
    <script type="text/javascript" src={% static '/js/bootstrap.min.js' %}></script>
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    {#这个js脚本是为了适配移动端布局,不过现在不需要了#}
{#    <script type="text/javascript" src={% static '/js/index.js' %}></script>#}


</head>
<body>

	<!-- 导航栏 -->
    {% include 'web/header.html' %}

	<!-- 主站内容 -->
	<div id="zan-bodyer">
		<div class="container">
			<div class="row">
				<!-- 左边的内容 -->
				<div id="mainstay" class="col-xs-8">
					<!-- 文章列表 -->
					<div id="article-list">
                        {% block content %}{% endblock content %}
					</div>
				</div>
				<!-- 右边的内容 -->
				<aside class="col-xs-4" id="sidebar">
					<!-- 搜索栏 -->
					<aside id="search">
							<form class="form-inline clearfix" method="post" id="searchform" action="/index">
                                {% csrf_token %}
							   <input class="form-control" type="text" name="s" id="s" placeholder="请输入要搜索的关键字">
							   <button type="submit" class="btn btn-danger btn-small" name="submit">
								   <i class="fa fa-search"></i>
								</button>
							</form>
					</aside>
					<!-- 快捷菜单 -->
					<aside id="sub_menu">
                        <a href="/index" class="btn btn-danger" role="button">网站首页</a>
                        <a href={% url 'article:diary_index' %} class="btn btn-danger" role="button">个人日记</a>
                        <a href={% url 'article:readme' %} class="btn btn-danger" role="button">关于本站</a>
                        <a href="#" class="btn btn-danger" role="button">Github</a>
					</aside>
					<!-- 快捷标签 -->
					<aside id="sub_tags">
						<div class="tags_head">快捷标签</div>
						<div class="tags_body">
							<a href={% url 'article:index' %}?tag=Python class="btn sub_label1" role="button">python</a>
							<a href={% url 'article:index' %}?tag=Django class="btn sub_label2" role="button">Django</a>
{#							<a href={% url 'article:index' %}?tag=Java class="btn sub_label1" role="button">Java</a>#}
{#							<a href={% url 'article:index' %}?tag=Mysql class="btn sub_label3" role="button">Mysql</a>#}
                            <a href={% url 'article:index' %}?tag=Mysql class="btn sub_label3" role="button">scrapy</a>
						</div>
					</aside>
				</aside>
			</div>
		</div>
	</div>

	<span class="pid">ID:80414367</span>

    {% include 'web/footer.html' %}

</body>
</html>

templates/web/base_diary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>#}
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href={% static '/css/bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static '/css/diary.css' %}>
    {% block css %}{% endblock %}
	<link rel="stylesheet" type="text/css" href={% static '/css/font-awesome.min.css '%}>
    <script type="text/javascript" src={% static '/js/jquery-1.12.4.min.js' %}></script>
    <script type="text/javascript" src={% static '/js/bootstrap.min.js' %}></script>
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
{#    <script type="text/javascript" src={% static '/js/index.js' %}></script>#}


</head>
<body>

	<!-- 导航栏 -->
    {% include 'web/header.html' %}

	<!-- 主站内容 -->
	<div id="zan-bodyer">
		<div class="container">
			<div class="row">
				<!-- 左边的内容 -->
				<div id="mainstay" class="col-xs-8">
					<!-- 文章列表 -->
					<div id="article-list">
                        {% block content %}{% endblock content %}
					</div>
				</div>
				<!-- 右边的内容 -->
				<aside class="col-xs-4" id="sidebar">
					<!-- 搜索栏 -->
					<aside id="search">
							<form class="form-inline clearfix" method="post" id="searchform" action="/diary">
                                {% csrf_token %}
							   <input class="form-control" type="text" name="s-d" id="s-d" placeholder="请输入要搜索的关键字">
							   <button type="submit" class="btn btn-danger btn-small" name="submit">
								   <i class="fa fa-search"></i>
								</button>
							</form>
					</aside>
					<!-- 快捷菜单 -->
					<aside id="sub_menu">
                        <a href="/index" class="btn btn-danger" role="button">网站首页</a>
                        <a href={% url 'article:diary_index' %} class="btn btn-danger" role="button">个人日记</a>
                        <a href={% url 'article:readme' %} class="btn btn-danger" role="button">关于本站</a>
                        <a href="#" class="btn btn-danger" role="button">Github</a>
					</aside>
				</aside>
			</div>
		</div>
	</div>

	<span class="pid">ID:80414367</span>

    {% include 'web/footer.html' %}

</body>
</html>

templates/web/diary.html
{% extends "web/base_diary.html" %}
{% load static %}
{% block title %}
    {{ art.title }}
{% endblock title %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static '/css/article_diary.css' %}>
{% endblock css %}


{% block content %}
    <div class="article">
        <div class="article-title">
            <p>{{ art.title }}</p>
        </div>
{#        <div class="tags">#}
{#                {% for tag in art.tags.all %}#}
{#                    <a href="#"><span class="label label-primary">{{ tag }}</span></a>#}
{#                {% endfor %}#}
{#        </div>#}
        <div class="article-content">
            <div class="contents">
                <!-- 缺文章 -->
                {{ art.text|safe }}
            </div>
        </div>
    </div>
{% endblock content %}

templates/web/footer.html
{% load static %}
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white" style="color: #ffffff">Copyright &copy; <a target="_blank" href="https://github.com/c59z">初雪hatsuyuki</a> 2022</p>
    </div>
</footer>
</footer>

templates/web/header.html
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container" id="myheader">

        <!-- 定义logo和切换小图标   -->
        <div class="navbar-header">

            <button class="navbar-toggle" data-toggle="collapse" data-target="#mymenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- <a href="#" class="navbar-brand">LOGO</a> -->
        </div>

        <div class="collapse navbar-collapse" id="mymenu">
            <!-- 定义菜单   -->
            <ul class="nav navbar-nav">
                <li><a href="/index">首页</a></li>
{#                <li><a href={% url 'article:index' %}>首页</a></li>#}
                <li><a href={% url 'article:diary_index' %}>日记</a></li>
                <li><a href="#">Github</a></li>
                <li><a href={% url 'article:readme' %}>ReadMe</a></li>
{#                <li><a href="#">留言</a></li>#}
            </ul>
        </div>
    </div>
</div>

<!-- 座右铭 -->
<div class="container motto">
    <p>白鸟可知悲哀，不染于天之蔚海之蓝，只徘徊于其间。</p>
</div>

templates/web/list.html
{% extends "web/base.html" %}
{% load static %}
{% block title %}
    本子昊牛逼
{% endblock title %}

{% block content %}
{% if search %}
    <div id="search_info">

            {% if articles %}
                <h4> <span style="color: white;font-size: 18px">关于 </span>  <span style="color: red;font-size: 18px">"{{ search }}"</span> <span style="color: white;font-size: 18px">搜索到以下内容:</span> </h4>
            {% else %}
                <h4> <span style="color: white;font-size: 18px">暂无关于 </span>  <span style="color: red;font-size: 18px">"{{ search }}"</span>  <span style="color: white;font-size: 18px">有关的文章。</span> </h4>
            {% endif %}

    </div>
{% endif %}
    {% for article in articles %}
        <div class="article">
            <div class="article-title">
                <a href={% url 'article:article' article.id %}>{{ article.title }}</a>
            </div>
            <div class="tags">
                {% for tag in article.tags.all %}
                    <a href={% url 'article:index' %}?tag={{ tag }}><span class="label label-primary">{{ tag }}</span></a>
                 {% endfor %}
            </div>
            <div class="article-content">
                <div class="contents">
                    <a href={% url 'article:article' article.id %}>{{ article.subtitle }}<br>
                    </a>
                </div>
            </div>
            <div class="article-date">
                <span>{{ article.created }}</span>
            </div>
        </div>
    {% endfor %}
    {#  下方翻页栏  #}
    <div class="page">
        <div class="pagination row">
            <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1" class="btn btn-success">
                    &laquo; 1
                </a>
                <a href="?page={{ articles.previous_page_number }}"
                   class="btn btn-info">
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
{#                                                            &tag={{ tag }}#}
                <a href="?page={{ articles.next_page_number }}"
                   class="btn btn-info">
                    {{ articles.next_page_number }}
                </a>
                <a href="?page={{ articles.paginator.num_pages }}"
                   class="btn btn-success">
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
            </div>
        </div>
    </div>

{% endblock content %}

templates/web/list_diary.html
{% extends "web/base_diary.html" %}
{% load static %}

{% block title %}
    我的日记
{% endblock title %}

{% block content %}
    {% if search %}
        <div id="search_info">

            {% if articles %}
                <h4><span style="color: white;font-size: 18px">关于 </span> <span
                        style="color: red;font-size: 18px">"{{ search }}"</span> <span
                        style="color: white;font-size: 18px">搜索到以下内容:</span></h4>
            {% else %}
                <h4><span style="color: white;font-size: 18px">暂无关于 </span> <span
                        style="color: red;font-size: 18px">"{{ search }}"</span> <span
                        style="color: white;font-size: 18px">有关的文章。</span></h4>
            {% endif %}

        </div>
    {% endif %}
    {% for article in articles %}

        <div class="row article diary-div center-block">

                {% if article.image_thumbnail %}
                {#                <div class="col-3">#}
                <div class="col-md-4 col-sm-4 col-xs-4">
                    <img src="{{ article.image_thumbnail.url }}" alt="image" style="max-width:100%; border-radius: 20px">
                </div>
            {% endif %}
            <!-- 文章内容 -->
            <div class="col-md-8 col-sm-8 col-xs-4">
                <!-- 标题 -->
                <h4>
                    <b>
                        <a href={% url 'article:diary' article.id %} style="color: black;text-shadow: 0 0 30px lightblue">
                            {{ article.title }}
                        </a>
                    </b>
                </h4>
                <!-- 子标题 -->
                <div class="sub-title">
                    <p style="color: white;">
                        {{ article.subtitle }}...
                    </p>
                </div>
                <!-- 创建时间 -->
                <p>
                    <span style="color: blue;">{{ article.created }}</span>
                </p>
            </div>
        </div>
    {% endfor %}

    {#  下方翻页栏  #}
    <div class="page">
        <div class="pagination row">
            <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1" class="btn btn-success">
                    &laquo; 1
                </a>
                <a href="?page={{ articles.previous_page_number }}"
                   class="btn btn-info">
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                {#                                                            &tag={{ tag }}#}
                <a href="?page={{ articles.next_page_number }}"
                   class="btn btn-info">
                    {{ articles.next_page_number }}
                </a>
                <a href="?page={{ articles.paginator.num_pages }}"
                   class="btn btn-success">
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
            </div>
        </div>
    </div>

{% endblock content %}

templates/web/readme.html
{% extends "web/base.html" %}
{% load static %}
{% block title %}
    ReadMe
{% endblock title %}
{% block css %}
    <link rel="stylesheet" type="text/css" href={% static '/css/article.css' %}>
{% endblock css %}


{% block content %}
    <div class="article">
        <div class="article-title">
            <p>ReadMe</p>
        </div>
        <div class="article-content">
            <div class="contents">
                <!-- 缺文章 -->
                <h3>关于站长</h3>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;(｡･∀･)ﾉﾞ嗨呀~你好,我是初雪,目前是一个平凡的大一新生,编程方面比较擅长Python和Java,前端苦手,正在自学日语,7月去考n2<br>
                </p>
                <h3>关于本站</h3>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;本站于2022年5月由一个高三的学生创作，目的是为了学习前后端的交互。<br>
                    本站后端采用了Django,前端使用了bootstrap。 <br>
                    因为初出茅庐,经验稀少,网站可能会发生意想不到的bug（不过我自己测试倒是没问题）
                    还请见谅。</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;虽说人生只有一次无论做出哪个选择都会后悔，但即便如此我还是想坚持做自己喜欢的事情,通过这个网站来分享一下微薄的经验<br></p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;我在这里,正是因为我还有没做完的事情在等着我</p>
                <h3>联系我</h3>
                <ul>
                    <li>我的QQ邮箱:1654911578@qq.com</li>
                    <li>我的网站:(现在还没有域名呜呜呜)</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}